### ISSUE TITLE
Time-based expiry of keys [JIRA: RIAK-2678]

### ISSUE THREAD

**Issue by michellep-basho** [basho/leveldb#107]
Adding per our discussion:

Similar to bitcask expiry of data based on a specified timeframe.  TBD whether this should be set at the bucket or bucket-type level.  Customer request.

**Comment by matthewvon** [comment]
leveldb has no concept of buckets or bucket-types.  The enhancement request needs to start in Riak.

**Comment by matthewvon** [comment]
mv-expiry branch merged to develop July 6, 2016 and beta launched July 7, 2016
