### ISSUE TITLE
clock_getres undefined symbol on ubuntu 12.04.4

### ISSUE THREAD

**Issue by dyu** [basho/leveldb#123]
It compiles but fails at runtime with clock_getres undefined symbol error.
I also found a similar error from google (https://drone.io/github.com/janelia-flyem/dvid/163)

**Comment by dyu** [comment]
And btw, I don't get this error on ubuntu 13.04.
Any idea what I'm missing on 12.04.4?

**Comment by matthewvon** [comment]
Best guess is that leveldb's build_detect_platform file is not working nicely with 12.04.4.  Look at the build_config.mk file in the leveldb directory.  Does the PLATFORM_LDFLAGS line (likely fourth from top) include "-lrc" within its setting.  If not, manually add it.  If "-lrc" is present, I am out of ideas.

**Comment by matthewvon** [comment]
Is this issue resolved?
