### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by vtolstov** [basho/leveldb#127]
Hi, sorry for maybe off-topic question. Does leveldb (mostly this fork) suitable for storing files in caching proxy server?

**Comment by matthewvon** [comment]
The response is more off-topic:  compared to what?  Apache caching, squid caching, mySql caching, etc … what size files and how often do they change?

**Comment by vtolstov** [comment]
Compared for none. I need in golang app store some files like debian packages, rpm packages (package proxy) and need to use some backend storage.  Does it leveldb sutable for this?

**Comment by matthewvon** [comment]
Is it capable of being a proxy cache backend end?  Yes.  Would I recommend it?  No.  These thoughts come to mind:
1.  I am assuming you would use the entire file as one "value".  leveldb could manage that, but it has to transition the entire file to and from memory both for your requests and for its compaction operations.  That seems painful if your files are greater than 1 megabyte.  Guessing you would be better storing the files in tiered directories and keeping the file location in leveldb.  Then you could access the files in chunks for transmission.
2.  I believe there are simple implementations of yum repositories that are available and more closely suit your needs.  I remember setting one up at my last company … but do not remember where the code originated.  Probably same for debian package libraries and such too.

**Comment by vtolstov** [comment]
Thanks for answers!
