### ISSUE TITLE
Compaction infinite loop

### ISSUE THREAD

**Issue by hyc** [basho/leveldb#135]
About 50% of the time, benchmark runs get hung up in an infinite compaction loop, triggered by the compactor deleting a file and forgetting that it was deleted. The test binary, command script used to trigger it, and the LOG files from the DB are included in http://highlandsun.com/hyc/bashobug.tgz

**Comment by hyc** [comment]
The benchmark was built with basho leveldb rev 16b22c8198975b62a938dff9910f4432772d253a.
The source code for the benchmark is here https://github.com/hyc/leveldb/tree/benches

**Comment by matthewvon** [comment]
I have reviewed the two LOG files in your .tgz.  I can see the problem there and understand what / why this is happening.  Will look for fix.  Likely have to put mutex back on-line during delete cycle … and move to alternate code of delay cycle deletes to one per minute.

**Comment by matthewvon** [comment]
mv-delete-mutex-fix reverts the change causing the compaction loop.  Please retest.

**Comment by hyc** [comment]
Thanks, just grabbed that and have been retesting, so far looks good but it will take several more runs just to be sure.

**Comment by hyc** [comment]
Looks good, no more hangs so far.

**Comment by matthewvon** [comment]
Closing issue as verified and fixed (https://github.com/basho/leveldb/pull/137).
