### ISSUE TITLE
db_bench 

### ISSUE THREAD

**Issue by dhdubois** [basho/leveldb#136]
We were doing testing using db_bench with an earlier release (when the tiering options were introduced) and have found that something has changed such that db_bench will either run very slowly or completely stop moving forward for reasonably large (100M key - 16 bytes/ value = 1024) readseq runs. Running on a fusion io ioCache card which had reasonable performance for the older versions.

**Comment by matthewvon** [comment]
Do you have specific command line settings for db_bench that caused the failure?

**Comment by dhdubois** [comment]
#!/bin/bash
Matthew-

Here is part of the script. What isn’t shown is that I create the database using a separate execution of db_bench with fillseq (or fillrand). All other options would be the same. I’m currently not using tiering.

This script works fine with the older version which I said is the first release you put up using tiering (which we are very interested in).

Thanks

Dave

# 

path="/mnt/iodrive2/dhd/bashodb"

#loc_path="/panfs/pas12a/vol1/dhd/bashodb" if using tiering use panasas at level 3

# Basho suggestions

# options.filter_policy=leveldb::NewBloomFilterPolicy2(16);

# Basho setting Bloom Bits, modified constructor for benchmark using

# basho NewBloomFilterPolicy2(FLAGS_bloom_bits)

bb=16

# options.block_cache=leveldb::NewLRUCache(536870912);

cs=536870912

# options.max_open_files=500;

of=500

# options.write_buffer_size=62914560;

wbs=62914560

# options.env=leveldb::Env::Default();

# Threads

t=1

r=100000000
vs=1024

time ~/workspace/leveldb-develop/db_bench \
                                                                --db=$path \
                                                                --benchmarks=readseq,stats \
                                                                --bloom_bits=$bb \
                                                                --compression_ratio=.5 \
                                                                --use_existing_db=1 \
                                                                --num=$r \
                                                                --threads=$t \
                                                                --value_size=$vs \
                                                                --cache_size=$cs \
                                                                --open_files=$of \
                                                                --write_buffer_size=$wbs

**Comment by matthewvon** [comment]
There is a second bug, #135, that included LOG and LOG.old files from their use of db_bench.  I already understand their problem, and it could be yours also.  We would know quickly if you started your test from scratch, then captured the LOG file once you feel the slow down.

**Comment by dhdubois** [comment]
Matthew-

Actually looks like fails during the fillseq with 100M items.

David DuBois
Los Alamos National Laboratory
Advanced Concepts Team, HPC-5
505-667-1732

**Comment by matthewvon** [comment]
mv-delete-mutex-fix has a quick revert causing issue #135.  Unclear if that is your performance problem.  Please retest.

**Comment by matthewvon** [comment]
If performance is still low, I would appreciate before / after statistics to compare to results here.  Then I can start digging.

**Comment by dhdubois** [comment]
I’ll let you know.

Thanks
Dave

**Comment by dhdubois** [comment]
Seems to have fixed the issue. I will continue testing and let you know if anything comes up.

Thanks

Dave

**Comment by matthewvon** [comment]
Closing issue as verified and fixed (https://github.com/basho/leveldb/pull/137).
