### ISSUE TITLE
Hot on/off switch for perf counters [JIRA: RIAK-1898]

### ISSUE THREAD

**Issue by matthewvon** [basho/leveldb#144]
The performance counters are atomic increments.  These do have some performance impact.  It would be really nice if they could be enabled and disable via the shared memory segment.  Then, the impact only occurs during developer work or when a user needs to find a problem in production.

**Comment by baotiao** [comment]
How did you want to implement you idea?  Adding a macro when we use gPerfCounter?

**Comment by matthewvon** [comment]
Mostly wanted to log the issue before it was forgotten (again).  The general answer is that the Inc() functions and such would check a flag in the shared memory segment before actually performing the atomic operation.  The catch is that the current code only allows the leveldb side to have write access to the shared memory segment.  Both leveldb and "user" would need write access.  Not a huge deal, just noting it.

**Comment by baotiao** [comment]
Why "user" need to have permission to write access? "User" only need to read the data produce by leveldb. if "user" can write the shared memory, it may cause conflict..

**Comment by DSomogyi** [comment]
.

**Comment by matthewvon** [comment]
Addressed / fixed here:  https://github.com/basho/leveldb/pull/161
