### ISSUE TITLE
write_buffer_size overwritten by gMapSize

### ISSUE THREAD

**Issue by matthewvon** [basho/leveldb#145]
The idea to make gMapSize a user option ended with it overwriting write_buffer_size in all cases.  This is really, really bad.  Heavily impacts performance.  Putting the correction into branch mv-sequential-tuning.  Fix is in db/db_impl.cc SanitizeOptions().

**Comment by matthewvon** [comment]
This was fixed by PR #146.

**Comment by andrewjstone** [comment]
Thanks @matthewvon
