### ISSUE TITLE
Clang build failure on FreeBSD 10.1 [JIRA: RIAK-1600]

### ISSUE THREAD

**Issue by fadushin** [basho/leveldb#149]
Hitting the following build errror when building with Clang on FreeBSD (now the default compiler, as of 10.0)

prompt$  CXX=c++ gmake

...

./include/leveldb/env.h:163:11: error: unknown type name 'pthread_t'; did you mean 'pthread'?
  virtual pthread_t StartThread(void (_function)(void_ arg), void\* arg) = 0;
          ^~~~~~~~~
          pthread
/usr/include/stdio.h:143:9: note: 'pthread' declared here
        struct pthread __fl_owner;      /_ current owner _/
               ^
In file included from db/log_reader.cc:8:
./include/leveldb/env.h:374:3: error: unknown type name 'pthread_t'; did you mean 'pthread'?
  pthread_t StartThread(void (_f)(void_), void_ a) {
  ^~~~~~~~~

the leveldb env.h file needs to include pthread.h, in order to fix this issue on this platform.

**Comment by matthewvon** [comment]
Fixed here:  https://github.com/basho/leveldb/pull/151
