### ISSUE TITLE
Infrequent, unreproducible missing SST

### ISSUE THREAD

**Issue by jonmeredith** [basho/leveldb#15]
We've seen a few instances of leveldb failing on compaction as it is missing an SST file

Example:

```
2012/06/12-20:23:41.713048 97 Generated table #422226: 563 keys, 2107848 bytes
88026049394855470996013819413191996189691609088/107719.sst: No such file or directory 
```

Possible theory is the file being added to the MANIFEST before actually being created on disk and then having problems during creation.

**Comment by matthewvon** [comment]
Issue found / resolved.  Riak was able to reopen a vnode before its close operation completed.  Took three passes at "fixing" the leveldb locking stuff ... but seems to be addressed.
