### ISSUE TITLE
Delete all leveldb key-values, while the disk usage doesn't reduce [JIRA: RIAK-1800]

### ISSUE THREAD

**Issue by jsvisa** [basho/leveldb#154]
I have a 14Gb data of leveldb files, I have delete it whole  with `eleveldb:iterator_move/2` and `eleveldb:delete/3`. When I'm going to fetch the first key in DB, it really took me to much time, 5min or longer, and the result showed the DB didn't have any keys anymore. But my disk usage remains 14Gb, I think leveldb didn't automatically `compaction` those keys. How could it be possible for me to show up it starting automatically compaction or not?

**Comment by matthewvon** [comment]
See https://github.com/basho/leveldb/wiki/mv-aggressive-delete, especially the section about "April 6 Update".  

Google's original leveldb implementation does not attempt to purge deleted data.  It waits until the delete marker moves all the way to the highest level through normal compactions.  Basho added "aggressive delete" to initiate additional compactions when delete markers are present.  The initial implementation however caused a heavy performance hit in some typical usage patterns.  The current implementation, as discussed in the "April 6 Update" section, only schedules compactions for delete markers found in levels 2 and above.  This can result in up to 4.2G of storage per Riak vnode remaining used.

**Comment by jsvisa** [comment]
Thanks @matthewvon  I'll watch it later
