### ISSUE TITLE
Change util/throttle.cc to use the port::Mutex and port::CondVar wrapper classes [JIRA: RIAK-2080]

### ISSUE THREAD

**Issue by paulplace** [basho/leveldb#167]
Currently, util/throttle.cc uses raw pthread_mutex_t and pthread_cond_t types rather than the corresponding wrapper classes in the porting layer. We should refactor the throttling code to use the wrapper classes.

Note that doing this will require updating port::CondVar, adding an overload of the Wait() method that takes a timeout parameter.

It would also be a good idea to add some unit tests that drive the port::Mutex, port::CondVar, and MutexLock classes.

**Comment by matthewvon** [comment]
resolved with branch pp-hot-threads-backport.  merged to develop branch ~Dec 2015.
