### ISSUE TITLE
leveldb.data_root ends up in /var/lib/riak/leveldb regardless of configuration value. [JIRA: RIAK-2470]

### ISSUE THREAD

**Issue by hongell** [basho/leveldb#189]
**riak config describe leveldb.data_root**

Documentation for leveldb.data_root
Where LevelDB will store its data.

   Valid Values:
     - the path to a directory
   Default Value : **$(platform_data_dir)/leveldb**
   Value not set in /etc/riak/riak.conf
   Internal key  : eleveldb.data_root

**riak config describe platform_data_dir**

Documentation for platform_data_dir
Platform-specific installation paths (substituted by rebar)

   Valid Values:
     - the path to a directory
   Default Value : /var/lib/riak
   Set Value     : **/datadisks/disk1/riak-data**
   Internal key  : riak_core.platform_data_dir

**1.8G    /var/lib/riak/leveldb/**

riak-2.1.3-1.el7.centos.x86_64 in Azure environment.

Even setting fixed path to leveldb.data_root in /etc/riak.conf wont do the change. Workarounding with symbolic link.

**Comment by matthewvon** [comment]
Would you attach your riak.conf?

**Comment by hongell** [comment]
anti_entropy = active
bitcask.data_root = $(platform_data_dir)/bitcask
bitcask.io_mode = erlang
buckets.default.allow_mult = true
check_crl = off
distributed_cookie = riak
dtrace = off
erlang.async_threads = 600
erlang.max_ets_tables = 3000000
erlang.max_ports = 1000000
erlang.process_limit = 1000000
leveldb.maximum_memory.percent = 40
listener.http.internal = 0.0.0.0:8098
listener.protobuf.internal = 0.0.0.0:8087
log.console = file
log.console.file = $(platform_log_dir)/console.log
log.console.level = info
log.crash.file = $(platform_log_dir)/crash.log
log.crash.maximum_message_size = 64KB
log.crash = on
log.crash.rotation = $D0
log.crash.rotation.keep = 5
log.crash.size = 10MB
log.error.file = $(platform_log_dir)/error.log
log.syslog = off
multi_backend.default = leveldb_mult
multi_backend.leveldb_mult.storage_backend = leveldb
multi_backend.memory_mult.memory_backend.max_memory_per_vnode = 50MB
multi_backend.memory_mult.memory_backend.ttl = 24h
multi_backend.memory_mult.storage_backend = memory
nodename = riak@10.0.1.10
nodename = riak@10.0.1.10
object.format = 1
object.siblings.maximum = 100
object.siblings.warning_threshold = 25
object.size.maximum = 50MB
object.size.warning_threshold = 5MB
platform_bin_dir = /usr/sbin
platform_data_dir = /mnt/resource/riak-data
platform_etc_dir = /etc/riak
platform_lib_dir = /usr/lib64/riak/lib
platform_log_dir = /mnt/resource/riak-logs
riak_control.auth.mode = off
riak_control = off
search = on
search.solr.jmx_port = 8985
search.solr.jvm_options = -d64 -Xms1g -Xmx1g -XX:+UseStringCache -XX:+UseCompressedOops
search.solr.port = 8093
search.solr.start_timeout = 30s
ssl.cacertfile = /vagrant/certs/ca.crt
ssl.certfile = /vagrant/certs/server.crt
ssl.keyfile = /vagrant/certs/server.key
storage_backend = multi
tls_protocols.tlsv1.1 = on
