### ISSUE TITLE
rewrite PosixEnv::Schedule() in env_posix.cc

### ISSUE THREAD

**Issue by matthewvon** [basho/leveldb#29]
Jesse pointed out that the current routine is bloated from a lot of copy/paste hacking.  Needs a rewrite, likely a supporting function for the queue item remove/add sequences.

**Comment by baotiao** [comment]
I have read the code. I want rewrite the codes.  You can assign thi issue to me ..
^-^

**Comment by matthewvon** [comment]
Work completed in mv-hot-threads2 and merged to master.
